import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Local fonts configuration
const proximaNova = localFont({
  src: [
    {
      path: '../../public/fonts/ProximaNova-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    // {
    //   path: '../../public/fonts/ProximaNova-Semibold.otf',
    //   weight: '600',
    //   style: 'normal',
    // },
    {
      path: '../../public/fonts/ProximaNova-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/ProximaNova-Extrabold.otf',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-proxima',
  display: 'swap',
});

const interstateCond = localFont({
  src: [
    {
      path: '../../public/fonts/InterstateCondensed-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/InterstateCondensed-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-interstate',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${proximaNova.variable} ${interstateCond.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
